plcs:
  EPS01:
    host: "192.168.1.254"
    port: 502
    unit_id: 1
    timeout: 3.0
    retries: 3
    description: "EPS Reactors Controller"
    vendor: "Honeywell"
    model: "HC900"
    addressing_scheme: "relative"
    max_concurrent_connections: 5
    health_check_interval: 15
    circuit_breaker_threshold: 5
    circuit_breaker_timeout: 30
