registers:
  PLC1_MANUFACTURING_LINE:
    # Coils (Digital Outputs) - Function Code 01/05
    1:
      name: "conveyor_motor_run"
      description: "Conveyor motor running status"
      data_type: "bool"
      units: "boolean"
      readonly: false
      critical: true

    2:
      name: "emergency_stop"
      description: "Emergency stop activated"
      data_type: "bool"
      units: "boolean"
      readonly: false
      critical: true

    3:
      name: "main_power"
      description: "Main power on/off"
      data_type: "bool"
      units: "boolean"
      readonly: false
      critical: true

    11:
      name: "station_1_active"
      description: "Station 1 active status"
      data_type: "bool"
      units: "boolean"
      readonly: false
      critical: false

    12:
      name: "station_2_active"
      description: "Station 2 active status"
      data_type: "bool"
      units: "boolean"
      readonly: false
      critical: false

    # Discrete Inputs (Digital Inputs) - Function Code 02
    10001:
      name: "safety_door_closed"
      description: "Safety door closed sensor"
      data_type: "bool"
      units: "boolean"
      readonly: true
      critical: true

    10002:
      name: "part_present_sensor"
      description: "Part present detection sensor"
      data_type: "bool"
      units: "boolean"
      readonly: true
      critical: false

    10003:
      name: "limit_switch_1"
      description: "Limit switch 1 status"
      data_type: "bool"
      units: "boolean"
      readonly: true
      critical: false

    10004:
      name: "limit_switch_2"
      description: "Limit switch 2 status"
      data_type: "bool"
      units: "boolean"
      readonly: true
      critical: false

    10011:
      name: "temperature_ok"
      description: "Temperature within acceptable range"
      data_type: "bool"
      units: "boolean"
      readonly: true
      critical: true

    # Input Registers (Read Only) - Function Code 04
    30001:
      name: "conveyor_speed_actual"
      description: "Actual conveyor speed"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "RPM"
      min_value: 0
      max_value: 3000
      readonly: true
      critical: false

    30002:
      name: "temperature_actual"
      description: "Actual process temperature"
      data_type: "uint16"
      scaling_factor: 0.1
      units: "°C"
      min_value: 0
      max_value: 500
      readonly: true
      critical: true
      dynamic: true

    30003:
      name: "motor_current_actual"
      description: "Actual motor current consumption"
      data_type: "uint16"
      scaling_factor: 0.1
      units: "A"
      min_value: 0
      max_value: 200
      readonly: true
      critical: true
      dynamic: true

    30004:
      name: "system_pressure"
      description: "Actual system pressure"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "PSI"
      min_value: 0
      max_value: 150
      readonly: true
      critical: true

    30011:
      name: "production_time"
      description: "Total production time"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "minutes"
      min_value: 0
      max_value: 65535
      readonly: true
      critical: false

    30012:
      name: "system_efficiency"
      description: "Overall system efficiency"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "%"
      min_value: 0
      max_value: 100
      readonly: true
      critical: false

    30013:
      name: "vibration_level"
      description: "Equipment vibration level"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "mm/s"
      min_value: 0
      max_value: 100
      readonly: true
      critical: true

    # Holding Registers (Read/Write) - Function Code 03/06/16
    40001:
      name: "conveyor_speed_setpoint"
      description: "Conveyor speed setpoint"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "RPM"
      min_value: 0
      max_value: 3000
      readonly: false
      critical: false

    40002:
      name: "temperature_setpoint"
      description: "Process temperature setpoint"
      data_type: "uint16"
      scaling_factor: 0.1
      units: "°C"
      min_value: 0
      max_value: 500
      readonly: false
      critical: true

    40003:
      name: "production_rate_target"
      description: "Production rate target"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "parts/min"
      min_value: 0
      max_value: 50
      readonly: false
      critical: false

    40011:
      name: "motor_current_limit"
      description: "Motor current limit setting"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "A"
      min_value: 0
      max_value: 200
      readonly: false
      critical: true

    40012:
      name: "pressure_setpoint"
      description: "System pressure setpoint"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "PSI"
      min_value: 0
      max_value: 150
      readonly: false
      critical: true

    40021:
      name: "part_counter"
      description: "Total parts produced counter"
      data_type: "uint32"
      scaling_factor: 1.0
      units: "count"
      min_value: 0
      max_value: 4294967295
      readonly: false
      critical: false
      dynamic: true

    40022:
      name: "good_parts_count"
      description: "Good parts count"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "count"
      min_value: 0
      max_value: 65535
      readonly: false
      critical: false

    40023:
      name: "rejected_parts_count"
      description: "Rejected parts count"
      data_type: "uint16"
      scaling_factor: 1.0
      units: "count"
      min_value: 0
      max_value: 65535
      readonly: false
      critical: false

    # System Status Enum Register
    40050:
      name: "system_mode"
      description: "Manufacturing line operating mode"
      data_type: "uint16"
      units: "enum"
      readonly: false
      critical: true
      enum_values:
        0: "STOPPED"
        1: "MANUAL"
        2: "AUTOMATIC"
        3: "MAINTENANCE"
        4: "EMERGENCY"

    40051:
      name: "alarm_status"
      description: "Active alarm status"
      data_type: "uint16"
      units: "bitfield"
      readonly: true
      critical: true
      bit_definitions:
        0: "Temperature High"
        1: "Pressure High"
        2: "Motor Overload"
        3: "Safety Door Open"
        4: "Emergency Stop"
        5: "Vibration High"
        6: "Part Jam"
        7: "Maintenance Due"

# Connection Configuration
connection:
  host: "localhost"
  port: 5020
  slave_id: 1
  timeout: 3
  retry_count: 3
  poll_interval: 1000 # milliseconds

# Metadata
metadata:
  plc_name: "Manufacturing Line Controller"
  location: "Production Floor A"
  firmware_version: "1.2.3"
  last_updated: "2024-01-15"
  description: "Main production line conveyor and process control"

# Data Logging Configuration
logging:
  enabled: true
  log_level: "INFO"
  dynamic_registers_only: false
  log_interval: 5000 # milliseconds
  archive_interval: 3600 # seconds

# Alarm Configuration
alarms:
  temperature_actual:
    high_alarm: 300
    high_warning: 280
    low_warning: 150
    low_alarm: 100

  motor_current_actual:
    high_alarm: 150
    high_warning: 120

  system_pressure:
    high_alarm: 120
    high_warning: 100
    low_warning: 20
    low_alarm: 10

  vibration_level:
    high_alarm: 80
    high_warning: 60
